### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [16]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)

## Player Count

* Display the total number of players

In [17]:
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [38]:
total_player = {'Total Players':[len(purchase_data['SN'].unique())]}
               
total_player1 = pd.DataFrame(total_player)
total_player1

   Total Players
0            576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [19]:
purchase_data.describe()

       Purchase ID         Age     Item ID       Price
count   780.000000  780.000000  780.000000  780.000000
mean    389.500000   22.714103   92.114103    3.050987
std     225.310896    6.659444   52.775943    1.169549
min       0.000000    7.000000    0.000000    1.000000
25%     194.750000   20.000000   48.000000    1.980000
50%     389.500000   22.000000   93.000000    3.150000
75%     584.250000   25.000000  139.000000    4.080000
max     779.000000   45.000000  183.000000    4.990000

In [20]:
purchase_data["Item Name"].head()

0    Extraction, Quickblade Of Trembling Hands
1                            Frenzied Scimitar
2                                 Final Critic
3                                  Blindscythe
4                                         Fury
Name: Item Name, dtype: object

In [21]:
Unique_Items = len(purchase_data["Item Name"].unique())
Unique_Items

179

In [42]:
avg_price = round(purchase_data['Price'].mean())
avg_price

3

In [23]:
total_purchases = round(purchase_data["Price"].sum())
total_purchases

2380.0

In [24]:
Purchase_analysis_total= {'Unique Items':[Unique_Items],'Average Price':[avg_price],'Number of Purchases': [len(purchase_data)],
                     'Total Purchases':[total_purchases]}
Purchase_analysis_total1 =pd.DataFrame(Purchase_analysis_total)
Purchase_analysis_total1 = Purchase_analysis_total1[['Unique Items','Average Price','Number of Purchases','Total Purchases']]
Purchase_analysis_total1

   Unique Items  Average Price  Number of Purchases  Total Purchases
0           179              3                  780           2380.0

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [25]:
gender = purchase_data["Gender"].value_counts()
gender1 = pd.DataFrame(gender)
gender1

                       Gender
Male                      652
Female                    113
Other / Non-Disclosed      15


## Purchasing Analysis (Gender)

In [26]:
male = purchase_data.groupby(['Gender']).get_group(('Male'))

male

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
30,30,Idai61,19,Male,140,Striker,2.94
31,31,Farusrian86,37,Male,179,"Wolf, Promise of the Moonwalker",4.48
32,32,Aeralria27,10,Male,133,Faith's Scimitar,4.09
33,33,Haillyrgue51,7,Male,44,Bonecarvin Battle Axe,2.38
...,...,...,...,...,...,...,...
746,746,Aellyria80,23,Male,159,"Oathbreaker, Spellblade of Trials",3.08
748,748,Rastynusuir31,20,Male,55,Vindictive Glass Edge,2.27
749,749,Chanossanya44,20,Male,53,Vengeance Cleaver,2.05
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

In [27]:
female = purchase_data.groupby(['Gender']).get_group(('Female'))

female

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
18,18,Reunasu60,22,Female,82,Nirvana,4.90
38,38,Reulae52,10,Female,116,Renewed Skeletal Katana,4.18
41,41,Assosia88,20,Female,7,"Thorn, Satchel of Dark Souls",1.33
55,55,Phaelap26,25,Female,84,Arcane Gem,3.79
66,66,Chanastsda67,21,Female,6,Rusty Skull,3.70
71,71,Hari50,20,Female,29,"Chaos, Ender of the End",1.98
72,72,Marilsa69,25,Female,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
76,76,Mindadaran26,13,Female,88,"Emberling, Defender of Delusions",3.75
81,81,Heudai45,8,Female,174,Primitive Blade,3.47
84,84,Jiskjask60,21,Female,34,Retribution Axe,2.22
85,85,Umolrian85,32,Female,33,Curved Axe,1.16
92,92,Chadistaya75,21,Female,39,"Betrayal, Whisper of Grieving Widows",3.94
112,112,Iskichinya81,21,Female,7,"Thorn, Satchel of Dark Souls",1.33
113,113,Phyali88,15,Female,140,Striker,2.94
117,117,Frichaststa61,21,Female,117,"Heartstriker, Legacy of the Light",1.79
119,119,Frichosia58,15,Female,87,"Deluge, Edge of the West",4.43
125,125,Yathecal82,20,Female,62,Piece Maker,1.87
134,134,Phyali88,15,Female,2,Verdict,2.48
140,140,Hari50,20,Female,8,"Purgatory, Gem of Regret",3.93
142,142,Adastirin33,35,Female,175,Woeful Adamantite Claymore,4.48
155,155,Aillyrin83,10,Female,98,"Deadline, Voice Of Subtlety",2.89
157,157,Marast30,18,Female,108,"Extraction, Quickblade Of Trembling Hands",3.53
166,166,Sondim68,22,Female,30,Stormcaller,2.21
169,169,Heosurnuru52,16,Female,123,Twilight's Carver,2.28
177,177,Syathe73,30,Female,135,Warped Diamond Crusader,1.40
178,178,Baelollodeu94,20,Female,57,"Despair, Favor of Due Diligence",4.60
196,196,Maradaran90,35,Female,9,"Thorn, Conqueror of the Corrupted",2.73
199,199,Ialallo29,15,Female,138,"Peacekeeper, Wit of Dark Magic",4.74
206,206,Haisurra41,20,Female,78,"Glimmer, Ender of the Moon",4.40
...,...,...,...,...,...,...,...
555,555,Pheosurllorin41,23,Female,7,"Thorn, Satchel of Dark Souls",1.33
558,558,Lassadarsda57,25,Female,108,"Extraction, Quickblade Of Trembling Hands",3.53
564,564,Chamjask73,22,Female,52,Hatred,4.84
569,569,Baelollodeu94,20,Female,87,"Deluge, Edge of the West",4.43
572,572,Yoishirrala98,17,Female,145,Fiery Glass Crusader,4.58
578,578,Aerithllora36,29,Female,153,Mercenary Sabre,3.74
579,579,Marilsa69,25,Female,12,Dawne,1.02
586,586,Chanirra79,23,Female,155,War-Forged Gold Deflector,1.01
588,588,Lassadarsda57,25,Female,15,Soul Infused Crystal,2.96
607,607,Rithe53,15,Female,80,Dreamsong,3.39
608,608,Leyirra83,24,Female,132,Persuasion,3.33
613,613,Quanrion96,21,Female,159,"Oathbreaker, Spellblade of Trials",3.08
615,615,Sida61,20,Female,72,Winter's Bite,3.77
618,618,Aisurdru79,29,Female,183,Dragon's Greatsword,1.09
641,641,Lisirra58,20,Female,49,"The Oculus, Token of Lost Worlds",2.96
653,653,Chamast86,32,Female,53,Vengeance Cleaver,2.05
658,658,Quilassa66,7,Female,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
666,666,Assilsan72,20,Female,82,Nirvana,4.90
667,667,Inasuir29,40,Female,66,Victor Iron Spikes,4.40
683,683,Ialallo29,15,Female,145,Fiery Glass Crusader,4.58
697,697,Tyaelistidru84,19,Female,1,Crucifer,3.26
698,698,Yarithrin84,30,Female,58,"Freak's Bite, Favor of Holy Might",4.14
699,699,Tyaelly53,17,Female,130,Alpha,2.07
714,714,Tyidaim51,16,Female,103,Singed Scalpel,4.35
727,727,Yathecal82,20,Female,104,Gladiator's Glaive,1.93
731,731,Eudanu84,22,Female,12,Dawne,1.02
740,740,Reunasu60,22,Female,127,"Heartseeker, Reaver of Souls",3.92
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
767,767,Ilmol66,8,Female,92,Final Critic,4.88
775,775,Aethedru70,21,Female,60,Wolf,3.54

In [28]:
other = purchase_data.groupby(['Gender']).get_group(('Other / Non-Disclosed'))

other

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
82,82,Haerithp41,16,Other / Non-Disclosed,160,Azurewrath,4.40
111,111,Sundim98,21,Other / Non-Disclosed,41,Orbit,4.75
228,228,Jiskirran77,20,Other / Non-Disclosed,80,Dreamsong,3.39
237,237,Idairin51,20,Other / Non-Disclosed,16,Restored Bauble,3.55
242,242,Eodaisu60,16,Other / Non-Disclosed,39,"Betrayal, Whisper of Grieving Widows",3.94
291,291,Idairin51,20,Other / Non-Disclosed,35,Heartless Bone Dualblade,3.45
350,350,Rairith81,15,Other / Non-Disclosed,34,Retribution Axe,2.22
401,401,Lirtim36,15,Other / Non-Disclosed,46,Hopeless Ebon Dualblade,1.33
484,484,Chanosian48,35,Other / Non-Disclosed,39,"Betrayal, Whisper of Grieving Widows",3.94
549,549,Maluncil97,25,Other / Non-Disclosed,146,Warped Iron Scimitar,3.10
629,629,Maluncil97,25,Other / Non-Disclosed,107,"Splitter, Foe Of Subtlety",2.18
637,637,Airi27,24,Other / Non-Disclosed,163,Thunderfury Scimitar,3.45
747,747,Siarithria38,38,Other / Non-Disclosed,146,Warped Iron Scimitar,3.10

In [29]:
total_gender = len(purchase_data["SN"].value_counts())

male = purchase_data.groupby(['Gender']).get_group(('Male'))
male1 = len(male["SN"].unique())

male_percent= round((male1/total_gender)*100,2)


female = purchase_data.groupby(['Gender']).get_group(('Female'))
female1 = len(female["SN"].unique())

female_percent= round((female1/total_gender)*100,2)


other =  purchase_data.groupby(['Gender']).get_group(('Other / Non-Disclosed'))
other1 = len(other["SN"].unique())

other_percent= round((other1/total_gender)*100,2)


Gender_df = {'Total Count':[male1, female1, other1],
             'Percentage Of Players':[male_percent, female_percent,other_percent]}
Gender_df1 = pd.DataFrame(Gender_df)

Gender_df1

   Total Count  Percentage Of Players
0          484                  84.03
1           81                  14.06
2           11                   1.91

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [30]:
gender_purchases = purchase_data.groupby('Gender')["SN"]

avg_by_gender_price = purchase_data.groupby('Gender')["Price"].mean()

total_purchase_value = purchase_data.groupby('Gender')["Price"].sum()

avg_per_person = (total_purchase_value / avg_by_gender_price)

gender_analysis = pd.DataFrame({"Purchase Count: " gender_purchases, "Average Purchase Price: " avg_by_gender, 
                               "Total Purchase Value: " total_purchase_value, "Avg Total Purchase Per Person: " avg_per_person})

SyntaxError: invalid syntax (<ipython-input-30-fac6bc6f49be>, line 9)

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [31]:
age_bins = [0, 9.90, 14.90, 19.90, 24.90, 29.90, 34.90, 39.90, 99999]
group_names = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40+"]

#database for age Demo
purchase_data["Age Demographics"]= pd.cut(purchase_data["Age"], age_bins, labels=group_names)
demographic_group =purchase_data.groupby("Age Demographics")

purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Demographics
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [32]:
top_spenders = purchase_data['Item ID'].groupby(purchase_data['SN']).count()

top_spenders= pd.DataFrame(data=top_spenders)
top_spenders.columns = ['Purchase Count']

top_spenders['Average Purchase Price'] = round(purchase_data['Price'].groupby(purchase_data['SN']).mean(),2)
top_spenders['Total Purchase Value'] = purchase_data['Price'].groupby(purchase_data['SN']).sum()


top_spenders.sort_values(by=['Total Purchase Value'], ascending=False, inplace=True)

top_spenders['Average Purchase Price'] = top_spenders['Average Purchase Price'].map('${:,.2f}'.format)
top_spenders['Total Purchase Value'] = top_spenders['Total Purchase Value'].map('${:,.2f}'.format)

top_spenders.head()

             Purchase Count Average Purchase Price Total Purchase Value
SN
Lisosia93                 5                  $3.79               $18.96
Idastidru52               4                  $3.86               $15.45
Chamjask73                3                  $4.61               $13.83
Iral74                    4                  $3.40               $13.62
Iskadarya95               3                  $4.37               $13.10

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [33]:
most_items = purchase_data.groupby(['Item ID', 'Item Name','Price'])['Price'].agg(['count','sum'])
most_items.columns = ['Purchase Count', 'Total Purchase Value']

most_items.reset_index(inplace=True)
most_items.set_index(['Item ID','Item Name'] ,inplace=True)

most_items = most_items[['Purchase Count', 'Price', 'Total Purchase Value']]

most_popular_items = most_items.sort_values(by='Purchase Count', ascending=False)

most_popular_items['Price'] = most_popular_items['Price'].map('${:,.2f}'.format)
most_popular_items['Total Purchase Value'] = most_popular_items['Total Purchase Value'].map('${:,.2f}'.format)

most_popular_items.head()

,,Purchase Count,Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$4.23,$50.76
145,Fiery Glass Crusader,9,$4.58,$41.22
108,"Extraction, Quickblade Of Trembling Hands",9,$3.53,$31.77
82,Nirvana,9,$4.90,$44.10
19,"Pursuit, Cudgel of Necromancy",8,$1.02,$8.16

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [34]:
most_profitable_items = most_items.sort_values(by='Total Purchase Value', ascending=False)

most_profitable_items['Price'] = most_profitable_items['Price'].map('${:,.2f}'.format)
most_profitable_items['Total Purchase Value'] = most_profitable_items['Total Purchase Value'].map('${:,.2f}'.format)
most_profitable_items.head()

,,Purchase Count,Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$4.23,$50.76
82,Nirvana,9,$4.90,$44.10
145,Fiery Glass Crusader,9,$4.58,$41.22
92,Final Critic,8,$4.88,$39.04
103,Singed Scalpel,8,$4.35,$34.80